matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: '12'

    - os: linux
      dist: bionic
      sudo: true
      language: node_js
      node_js: '12'
      addons:
        apt:
          packages:
            - gcc-multilib
            - g++-multilib
            - libx11-dev
            - zlib1g-dev
            - libpng-dev
            - libxtst-dev
            - libx11:i686
            - zlib1g:i686
            - libpng:i686
            - libxtst:i686

script:
  - npm run dist
